### ISSUE TITLE
there is no GUI

### ISSUE THREAD

**Issue by greyltc** [greyltc/solar-sim-software#2]
Controlling the collection of solar cell data is done through interaction with a command line program, `mutovis-control-cli`
A GUI would be nice! Especially for monitoring the data as its collected.

**Comment by greyltc** [comment]
work still in progress
this will be the entry point: https://github.com/mutovis/control-software/blob/master/mutovis-control-gui

**Comment by greyltc** [comment]
@rbrenesh
To slightly alleviate this problem today, I've solved https://github.com/mutovis/analysis-software/issues/3
This means that by picking your data collection folder by using the File --> Watch menu item in `mutovis-analysis`, your measurement results will show up in the table automatically as soon as the data collection file has been closed by the measurement program. It's not quite real-time data monitoring, but it's getting at least closer!

**Comment by rbrenesh** [comment]
I tried using the Watch mode after updating the program using:

`yay -S python-mutovis-analysis`

I don't know if you have pushed the update to the package manager but when I enable the Watch feature the app is crashing and I'm getting this error:

`Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/batch_iv_analysis/gui.py", line 1182, in handleWatchAction
    self.handleWatchUpdate(self.workingDirectory)
  File "/usr/lib/python3.7/site-packages/batch_iv_analysis/gui.py", line 1233, in handleWatchUpdate
    self.newFiles(new_files_fp)
  File "/usr/lib/python3.7/site-packages/batch_iv_analysis/gui.py", line 899, in newFiles
    self.analyzer.processFiles(fullPaths, self.processFitResult, self.primeRow)
  File "/usr/lib/python3.7/site-packages/batch_iv_analysis/ivAnalyzer.py", line 305, in processFiles
    fileDatas = ivAnalyzer._loadFile(fullPath)
  File "/usr/lib/python3.7/site-packages/batch_iv_analysis/ivAnalyzer.py", line 374, in _loadFile
    iv_data = pixel['all_measurements']          
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/lib/python3.7/site-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'all_measurements' doesn't exist)"
Aborted (core dumped)`

**Comment by greyltc** [comment]
hm. looks like maybe there is a malformed file in the directory you're watching (from a run that was aborted before the h5 file was completely written maybe?). Anyway, this should obviously be handled properly.

Does watch work if you start watching an empty directory to start?

**Comment by rbrenesh** [comment]
Yeah you're totally right. I was doing some test runs and aborted one, once I deleted that run it was back to normal.

**Comment by greyltc** [comment]
But the tool needs to be robust to that. Do you still have the bad file you can send me?

**Comment by greyltc** [comment]
the crash from https://github.com/mutovis/control-software/issues/2#issuecomment-468447573 is solved: https://github.com/mutovis/analysis-software/issues/7
